name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: checkout branch
        uses: actions/checkout@v4

      - name: Setup .Net Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Build dotnet
        run: dotnet build --configuration Release

      - name: DotNet publish
        run: dotnet publish src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj --configuration Release -o artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: artifacts/
